### ISSUE TITLE
models.js niet geladen

### ISSUE THREAD

**Issue by fredottenhof** [tomkooij/modelleertaal#43]
Probeer modelleertaal in eigen website te hangen, om leerlingen aan te zetten tot oefenen met meer dan alleen de examenvoorbeelden, conform denken over "leren door volgen verken-modelleer-experimenteer-cyclus". 
Kom hobbeltje tegen: bij opstarten verschijnt melding "models.js niet geladen", kan bibliotheek niet langs die weg benaderen. Anderszins geladen model wordt ook niet geopend.

Instructie in readme is niet helemaal helder.
File modelleertaal-app.js bestaat en is geladen, in root, maar modelleertaal-app.browser.js niet. Elders wordt gesproken over modelleertaal-app-browser.js; welke naam is de juiste ?
Niet duidelijk of die file moet worden geplaatst in folder /scripts.

Alle permutaties van naam en plaats geprobeerd; geen enkele werkt.
Gaarne even helpen over hobbeltje heen te komen.

**Comment by tomkooij** [comment]
`model.js` niet geladen is blijkbaar niet de juiste foutmelding, want hier zo `modelleertaal-app.browser.js not found` ofzo op zijn plaats zijn :(

Ik *dacht* dat de juiste files te downloaden waren/zijn via "Releases". Maar dat klopt niet. Ik zie dat `scripts/modelleertaal-app.browser.js` daar niet in zit...

Ik ga zorgen dat ze daar wel terecht komen. (Daar maak ik een nieuw issue voor).

Maar ze zijn ondertussen hier te vinden:
https://github.com/tomkooij/modelleertaal/tree/gh-pages/scripts

Het relevante bestand is:
https://raw.githubusercontent.com/tomkooij/modelleertaal/gh-pages/scripts/modelleertaal-app.browser.js

**Comment by tomkooij** [comment]
Inmiddels opgelost. De bestanden zijn (weer) te vinden in de laatste release:
https://github.com/tomkooij/modelleertaal/releases/download/v5.0.2/modelleertaal-v5.0.2.zip

**Comment by fredottenhof** [comment]
Tom,

Prima. Ik had hem inmiddels al geladen. Werkt nu prima. Dank.

Overigens ook gekeken naar die opgaven-bibliotheek Quantummechanica die jouw collega heeft gemaakt. Mooi spul.
Ik zit met mijn ideeën verder: opgaven in een database, met aangeven zwaarte (aantal scorepunten) en verdere uitbreidingen.

Fred.
