### ISSUE TITLE
De sin, cos en tan functies gebruiken verschillende eenheden

### ISSUE THREAD

**Issue by mierenhoop** [tomkooij/modelleertaal#46]
https://github.com/tomkooij/modelleertaal/blob/e04afe34e42e917606d156b3bdd71c44799035f4/evaluator.js#L326-L331
Op de eerste drie lijnen wordt de inputvariabele van graden omgezet in een radiale omdat de functie in javascript een radiale gebruikt, maar hij output een radiale, net als alle andere functies die eronder staan. Het is verwarrend om overal radialen te gebruiken behalve op drie plekken.

**Comment by emma-miler** [comment]
Het lijkt mij zinvol om de functies sinr, cosr en tanr toe te voegen die in radialen werken, om zo niet backwards compatibility te verliezen.

**Comment by tomkooij** [comment]
@mierenhoop @emma-miler Het is zo verwarrend/onlogisch omdat modelleertaal hier letterlijk de modellen volgt die in examens gebruikt worden. En **helaas** die gebruiken radialen en graden door elkaar.

Het is nu verwarrend, maar de examenmodellen werken zoals ze in de examenopgaven staan...

Beetje flauw, maar: "PRs zijn welkom voor sinr, cosr en tanr".
