### ISSUE TITLE
Vreemde kleuren in scherm

### ISSUE THREAD

**Issue by MartijnStobbelaar** [tomkooij/modelleertaal#48]
![image](https://user-images.githubusercontent.com/78735091/107217359-5ac6da80-6a0e-11eb-919e-f3cf50dba603.png)
Een leerling van mij krijgt deze achtergrond kleuren bij het draaien van een model. Weet jij waar dit aan ligt?
alvast bedankt.
Martijn Stobbelaar

**Comment by tomkooij** [comment]
@MartijnStobbelaar 

Nog niet eerder gezien.

Welke browser/OS/device? Als ik het kan reproduceren, dan kan ik het wellicht oplossen.

(Gebruik eventueel: https://www.whatismybrowser.com/)

**Comment by MartijnStobbelaar** [comment]
Hallo Tom,

Het was een leerling uit mijn klas die als browser Edge gebruikte op een windows 10 machine.
Zij gaf aan dat het ook andere kleuren werden als ze parameters in het model veranderde.
Ik ben heel benieuwd of je hier achter kan komen.

Met vriendelijke groeten,

Martijn Stobbelaar

**Comment by tomkooij** [comment]
Het lukt mij helaas vooralsnog niet dit te reproduceren:
![image](https://user-images.githubusercontent.com/6316468/108323985-a2482600-71c7-11eb-82ab-f24e0ff86aaf.png)

Het model staat hier: https://gist.github.com/tomkooij/6a7a81144b2b04c8a641713695231710 (zodat ik zelf kan debuggen)
